### ISSUE TITLE
Documentation improvements: Concurrent requests and handling of messages without callback

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/NServiceBus.Callbacks#52] opened 2017-02-24 15:48 UTC
I think the documentation https://docs.particular.net/nservicebus/messaging/callbacks should be improved. I figured these things out only by analyzing the implementation:
- Concurrent requests are possible, because the correlation ID is used for dispatching the replies.
- Messages are moved to the error queue if a callback is missing, e.g., because of a process crash.

Furthermore, this paragraph is confusing:
> To handle responses from the processing endpoint, the sending endpoint must have it's own queue. Therefore, the sending endpoint cannot be configured as a SendOnly endpoint. Messages arriving in this queue are handled using a message handler, similar to that of the processing endpoint, as shown: [...]

Sounds as if you would have to setup a message handler for receiving the reply, but actually you only have to set up a message handler for sending the reply.

**Comment by timbussmann** [comment] 2017-03-06 16:54
> Messages are moved to the error queue if a callback is missing, e.g., because of a process crash.

Afaik, messages which should be handled by a callback but no callback was found aren't moved to the error queue. Can you clarify the scenario which would lead to a message in the error queue?

> Sounds as if you would have to setup a message handler for receiving the reply, but actually you only have to set up a message handler for sending the reply.

I think this page is confusing because it seems to document handling response messages in general (which are just regular messages handled via message handlers) and responses handled via callbacks. So without callbacks, you would indeed need message handlers.

**Comment by Niklas-Peter** [comment] 2017-03-09 18:49
https://docs.particular.net/nservicebus/handlers/#behavior-when-there-is-no-handler-for-a-message

@timbussmann From this section I concluded that a callback response would also be moved to the error queue or is there some special handling for callback replies?

**Comment by timbussmann** [comment] 2017-03-10 06:56
@Niklas-Peter yeah the doc on the RequestResponseExtensions seems to be wrong indeed. It might also make sense to describe that behavior explicitly in the callbacks documentation page 👍

**Comment by timbussmann** [comment] 2017-03-10 07:21
@Niklas-Peter I think I stated the behavior icorrectly, 
* in case a response message arrives and has no associated callback registered and no message handler, the message should go to the error queue
* in case a response message arrives and has no associated callback registered but a regular message handler exists, the message is handled by the message handler and is not moved to the error queue

can you verify this aligns with what you're seeing?

**Comment by Niklas-Peter** [comment] 2017-03-10 07:25
@timbussmann No, the first bullet point is different from my observations. The message did not go to the error queue in this case.

**Comment by danielmarbach** [comment] 2017-03-10 07:36
```
       [Test]
       public async Task ShouldNot_trigger_the_callback_when_canceled()
       {
           OperationCanceledException exception = null;

           var context = await Scenario.Define<Context>()
               .WithEndpoint<Replier>()
               .WithEndpoint<EndpointWithLocalCallback>(b => b.When(async (bus, ctx) =>
               {
                   var cs = new CancellationTokenSource();
                   ctx.TokenSource = cs;

                   var options = new SendOptions();

                   try
                   {
                       ctx.Response = await bus.Request<MyResponse>(new MyRequest(), options, cs.Token);
                       ctx.CallbackFired = true;
                   }
                   catch (OperationCanceledException e)
                   {
                       exception = e;
                   }
               }).DoNotFailOnErrorMessages())
               .Done(c => c.FailedMessages.Any())
               .Run();

           var message = context.FailedMessages.SelectMany(x => x.Value).Single();
           Assert.IsNull(context.Response);
           Assert.False(context.CallbackFired);
           Assert.True(context.HandlerGotTheRequest);
           Assert.IsInstanceOf<OperationCanceledException>(exception);
       }
```

![image](https://cloud.githubusercontent.com/assets/174258/23786323/a8b1a000-056c-11e7-88cf-7da2f2d9e027.png)

I will add this acceptance test to develop

**Comment by andreasohlund** [comment] 2017-03-15 15:48
>No, the first bullet point is different from my observations. The message did not go to the error queue in this case.

@Niklas-Peter can you reliably reproduce this?

**Comment by Niklas-Peter** [comment] 2017-04-01 11:33
@andreasohlund Maybe I did something wrong, but using this code the message does NOT appear in ServicePulse as failed message.

1. Start "Requester" and send a request.
2. Close "Requester".
3. Start "Replier" and wait until it sent the reply.
4. Close "Replier".
5. Start "Requester": The reply is removed from the channel, but I do not what happens with it. It is not shown in ServicePulse and I do not get any information in the Requester's console.

[UnhandledSyncReply.zip](https://github.com/Particular/NServiceBus.Callbacks/files/887573/UnhandledSyncReply.zip)

**Comment by andreasohlund** [comment] 2017-04-03 14:43
Thanks @Niklas-Peter I'll try your repro

**Comment by andreasohlund** [comment] 2017-04-04 09:24
@Niklas-Peter I can confirm that the message doesn't go to the error q.

The reason is that you're using the style of callbacks that only sends an `int` etc back and that will be going across the wire as a control message. Since there can't be any handlers for it we've decided to not move this to the error queue since that would be just noise and there is no "message loss" since the only thing that can be waiting is a volatile callback.

I propose the following actions:

* Raise issue to have the callbacks package log a warning when this happens
* Update documentation accordingly


@Particular/nservicebus-maintainers @danielmarbach thoughts?

**Comment by Niklas-Peter** [comment] 2017-04-07 18:12
> there is no "message loss" since the only thing that can be waiting is a volatile callback.

Frankly, I think there is a message loss. Yes, if you use synchronous request-reply you should know about such problem, but I think it should still be considered an error. Especially, the handling of a primitive response type (int, ...) should not be different from the handling of other response types. That would be confusing.

**Comment by andreasohlund** [comment] 2017-04-07 18:13
In this case sending the message to the error queue would be pointless since there is no way you can recover by retrying the message? (Ie it would just be noise from an ops perspective?)

**Comment by Niklas-Peter** [comment] 2017-04-07 18:20
Yes, but it is still good to know that there went something wrong, even if you can not recover by retrying the message. OK, if you log a warning/error with sufficient information you can also find this information in the log. That makes sense, because it prevents from retrying a message with no chance for success in ServicePulse.

Can you recover by retrying the message if the response type is non-primitive? I think that would only be possible if there was another usual/persistent handler handling the same response type or does a synchronous reply message have some special tag that prevents it to be received by an usual handler?

**Comment by andreasohlund** [comment] 2017-04-10 07:38
>Yes, but it is still good to know that there went something wrong, even if you can not recover by retrying the message. OK, if you log a warning/error with sufficient information you can also find this information in the log. That makes sense, because it prevents from retrying a message with no chance for success in ServicePulse.

Yea, we'll make sure to log a warning, https://github.com/Particular/NServiceBus.Callbacks/issues/60

>Can you recover by retrying the message if the response type is non-primitive? 

Potentially yes since there can exist message handlers as well for the message

>I think that would only be possible if there was another usual/persistent handler handling the same response type or does a synchronous reply message have some special tag that prevents it to be received by an usual handler?

Correct but since we can't know for sure if there should be a handler for the message we have to play it safe and move it to the error queue to make sure that there is no message loss.

Does this make ant sense?

**Comment by andreasohlund** [comment] 2017-04-10 08:03
@Niklas-Peter docs PR raised, does it make sense? https://github.com/Particular/docs.particular.net/pull/2625

Closing this since the actions are covered by:

https://github.com/Particular/docs.particular.net/pull/2625

and
https://github.com/Particular/NServiceBus.Callbacks/issues/60

**Closed by andreasohlund** 2017-04-10 08:03 UTC
